In [66]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans, DBSCAN
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler

In [3]:
dflm = pd.read_csv('E:/KrishM/PythonPrjs/PyDatasets/moneylaunder/ML.csv')

In [4]:
dflm

,typeofaction,sourceid,destinationid,amountofmoney,date,isfraud,typeoffraud
0,cash-in,30105,28942,494528,2019-07-19 14:40:00,1,type1
1,cash-in,30105,8692,494528,2019-05-17 14:57:00,1,type1
2,cash-in,30105,60094,494528,2019-07-20 13:20:00,1,type1
3,cash-in,30105,20575,494528,2019-07-03 14:15:00,1,type1
4,cash-in,30105,45938,494528,2019-05-26 10:40:00,1,type1
...,...,...,...,...,...,...,...
2335,transfer,14945,43793,106907,2019-03-29 14:53:00,0,none
2336,transfer,9532,43793,106907,2019-04-13 13:19:00,0,none
2337,transfer,27332,43793,106907,2019-05-10 09:34:00,0,none
2338,transfer,32685,43793,106907,2019-07-08 12:20:00,0,none
2339,transfer,26390,43793,106907,2019-03-25 13:52:00,0,none

In [5]:
dflm['typeofaction'].value_counts()

transfer    1580
cash-in      760
Name: typeofaction, dtype: int64

In [6]:
dflm['typeofaction'].unique()

array(['cash-in', 'transfer'], dtype=object)

In [7]:
dflm['amountofmoney'].value_counts()

226479     27
274171     27
362164     24
5815280    24
274713     24
           ..
1162767     1
2084373     1
3384858     1
3999274     1
4849662     1
Name: amountofmoney, Length: 933, dtype: int64

In [8]:
dflm.dtypes

typeofaction     object
sourceid          int64
destinationid     int64
amountofmoney     int64
date             object
isfraud           int64
typeoffraud      object
dtype: object

In [9]:
dflm['date'] = pd.to_datetime(dflm['date'])

In [10]:
dflm['date']

0      2019-07-19 14:40:00
1      2019-05-17 14:57:00
2      2019-07-20 13:20:00
3      2019-07-03 14:15:00
4      2019-05-26 10:40:00
               ...
2335   2019-03-29 14:53:00
2336   2019-04-13 13:19:00
2337   2019-05-10 09:34:00
2338   2019-07-08 12:20:00
2339   2019-03-25 13:52:00
Name: date, Length: 2340, dtype: datetime64[ns]

In [11]:
dflm.dtypes

typeofaction             object
sourceid                  int64
destinationid             int64
amountofmoney             int64
date             datetime64[ns]
isfraud                   int64
typeoffraud              object
dtype: object

In [14]:
dflm[dflm['date'] > '2019-06-01 00:00:00']

,typeofaction,sourceid,destinationid,amountofmoney,date,isfraud,typeoffraud
0,cash-in,30105,28942,494528,2019-07-19 14:40:00,1,type1
2,cash-in,30105,60094,494528,2019-07-20 13:20:00,1,type1
3,cash-in,30105,20575,494528,2019-07-03 14:15:00,1,type1
7,cash-in,30105,1020,494528,2019-07-04 08:59:00,1,type1
9,cash-in,30105,82016,494528,2019-06-09 12:27:00,1,type1
...,...,...,...,...,...,...,...
2323,transfer,30714,43793,106907,2019-06-28 14:35:00,0,none
2325,transfer,10908,43793,106907,2019-06-10 15:27:00,0,none
2330,transfer,37235,43793,106907,2019-07-02 14:21:00,0,none
2333,transfer,53540,43793,106907,2019-06-27 12:39:00,0,none
2338,transfer,32685,43793,106907,2019-07-08 12:20:00,0,none

In [15]:
dflm['date_year'] = dflm['date'].dt.year

,typeofaction,sourceid,destinationid,amountofmoney,date,isfraud,typeoffraud,date_year
0,cash-in,30105,28942,494528,2019-07-19 14:40:00,1,type1,2019
1,cash-in,30105,8692,494528,2019-05-17 14:57:00,1,type1,2019
2,cash-in,30105,60094,494528,2019-07-20 13:20:00,1,type1,2019
3,cash-in,30105,20575,494528,2019-07-03 14:15:00,1,type1,2019
4,cash-in,30105,45938,494528,2019-05-26 10:40:00,1,type1,2019
...,...,...,...,...,...,...,...,...
2335,transfer,14945,43793,106907,2019-03-29 14:53:00,0,none,2019
2336,transfer,9532,43793,106907,2019-04-13 13:19:00,0,none,2019
2337,transfer,27332,43793,106907,2019-05-10 09:34:00,0,none,2019
2338,transfer,32685,43793,106907,2019-07-08 12:20:00,0,none,2019
2339,transfer,26390,43793,106907,2019-03-25 13:52:00,0,none,2019

In [17]:
dflm['date_month'] = dflm['date'].dt.month

In [18]:
dflm

,typeofaction,sourceid,destinationid,amountofmoney,date,isfraud,typeoffraud,date_year,date_month
0,cash-in,30105,28942,494528,2019-07-19 14:40:00,1,type1,2019,7
1,cash-in,30105,8692,494528,2019-05-17 14:57:00,1,type1,2019,5
2,cash-in,30105,60094,494528,2019-07-20 13:20:00,1,type1,2019,7
3,cash-in,30105,20575,494528,2019-07-03 14:15:00,1,type1,2019,7
4,cash-in,30105,45938,494528,2019-05-26 10:40:00,1,type1,2019,5
...,...,...,...,...,...,...,...,...,...
2335,transfer,14945,43793,106907,2019-03-29 14:53:00,0,none,2019,3
2336,transfer,9532,43793,106907,2019-04-13 13:19:00,0,none,2019,4
2337,transfer,27332,43793,106907,2019-05-10 09:34:00,0,none,2019,5
2338,transfer,32685,43793,106907,2019-07-08 12:20:00,0,none,2019,7
2339,transfer,26390,43793,106907,2019-03-25 13:52:00,0,none,2019,3

In [19]:
dflm['date_day'] = dflm['date'].dt.day

In [20]:
dflm

,typeofaction,sourceid,destinationid,amountofmoney,date,isfraud,typeoffraud,date_year,date_month,date_day
0,cash-in,30105,28942,494528,2019-07-19 14:40:00,1,type1,2019,7,19
1,cash-in,30105,8692,494528,2019-05-17 14:57:00,1,type1,2019,5,17
2,cash-in,30105,60094,494528,2019-07-20 13:20:00,1,type1,2019,7,20
3,cash-in,30105,20575,494528,2019-07-03 14:15:00,1,type1,2019,7,3
4,cash-in,30105,45938,494528,2019-05-26 10:40:00,1,type1,2019,5,26
...,...,...,...,...,...,...,...,...,...,...
2335,transfer,14945,43793,106907,2019-03-29 14:53:00,0,none,2019,3,29
2336,transfer,9532,43793,106907,2019-04-13 13:19:00,0,none,2019,4,13
2337,transfer,27332,43793,106907,2019-05-10 09:34:00,0,none,2019,5,10
2338,transfer,32685,43793,106907,2019-07-08 12:20:00,0,none,2019,7,8
2339,transfer,26390,43793,106907,2019-03-25 13:52:00,0,none,2019,3,25

In [22]:
dflm['date_week'] = dflm['date'].dt.isocalendar().week

In [23]:
dflm

,typeofaction,sourceid,destinationid,amountofmoney,date,isfraud,typeoffraud,date_year,date_month,date_day,date_week
0,cash-in,30105,28942,494528,2019-07-19 14:40:00,1,type1,2019,7,19,29
1,cash-in,30105,8692,494528,2019-05-17 14:57:00,1,type1,2019,5,17,20
2,cash-in,30105,60094,494528,2019-07-20 13:20:00,1,type1,2019,7,20,29
3,cash-in,30105,20575,494528,2019-07-03 14:15:00,1,type1,2019,7,3,27
4,cash-in,30105,45938,494528,2019-05-26 10:40:00,1,type1,2019,5,26,21
...,...,...,...,...,...,...,...,...,...,...,...
2335,transfer,14945,43793,106907,2019-03-29 14:53:00,0,none,2019,3,29,13
2336,transfer,9532,43793,106907,2019-04-13 13:19:00,0,none,2019,4,13,15
2337,transfer,27332,43793,106907,2019-05-10 09:34:00,0,none,2019,5,10,19
2338,transfer,32685,43793,106907,2019-07-08 12:20:00,0,none,2019,7,8,28
2339,transfer,26390,43793,106907,2019-03-25 13:52:00,0,none,2019,3,25,13

In [31]:
dflm['date_secs'] = dflm['date'].dt.second

In [34]:
dflm

,typeofaction,sourceid,destinationid,amountofmoney,date,isfraud,typeoffraud,date_year,date_month,date_day,date_week,date_secs,date_hour,date_mins
0,cash-in,30105,28942,494528,2019-07-19 14:40:00,1,type1,2019,7,19,29,0,14,40
1,cash-in,30105,8692,494528,2019-05-17 14:57:00,1,type1,2019,5,17,20,0,14,57
2,cash-in,30105,60094,494528,2019-07-20 13:20:00,1,type1,2019,7,20,29,0,13,20
3,cash-in,30105,20575,494528,2019-07-03 14:15:00,1,type1,2019,7,3,27,0,14,15
4,cash-in,30105,45938,494528,2019-05-26 10:40:00,1,type1,2019,5,26,21,0,10,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2335,transfer,14945,43793,106907,2019-03-29 14:53:00,0,none,2019,3,29,13,0,14,53
2336,transfer,9532,43793,106907,2019-04-13 13:19:00,0,none,2019,4,13,15,0,13,19
2337,transfer,27332,43793,106907,2019-05-10 09:34:00,0,none,2019,5,10,19,0,9,34
2338,transfer,32685,43793,106907,2019-07-08 12:20:00,0,none,2019,7,8,28,0,12,20
2339,transfer,26390,43793,106907,2019-03-25 13:52:00,0,none,2019,3,25,13,0,13,52

In [39]:
dflm.drop(dflm.iloc[:, 7:], inplace=True, axis=1)

In [40]:
dflm

,typeofaction,sourceid,destinationid,amountofmoney,date,isfraud,typeoffraud
0,cash-in,30105,28942,494528,2019-07-19 14:40:00,1,type1
1,cash-in,30105,8692,494528,2019-05-17 14:57:00,1,type1
2,cash-in,30105,60094,494528,2019-07-20 13:20:00,1,type1
3,cash-in,30105,20575,494528,2019-07-03 14:15:00,1,type1
4,cash-in,30105,45938,494528,2019-05-26 10:40:00,1,type1
...,...,...,...,...,...,...,...
2335,transfer,14945,43793,106907,2019-03-29 14:53:00,0,none
2336,transfer,9532,43793,106907,2019-04-13 13:19:00,0,none
2337,transfer,27332,43793,106907,2019-05-10 09:34:00,0,none
2338,transfer,32685,43793,106907,2019-07-08 12:20:00,0,none
2339,transfer,26390,43793,106907,2019-03-25 13:52:00,0,none

In [41]:
dflm['typeofaction'].value_counts()

transfer    1580
cash-in      760
Name: typeofaction, dtype: int64

In [45]:
dftoa = pd.get_dummies(dflm['typeofaction'], prefix='toa')

In [46]:
dflmerge = pd.concat([dflm, dftoa], axis=1)

In [47]:
dflmerge

,typeofaction,sourceid,destinationid,amountofmoney,date,isfraud,typeoffraud,toa_cash-in,toa_transfer
0,cash-in,30105,28942,494528,2019-07-19 14:40:00,1,type1,1,0
1,cash-in,30105,8692,494528,2019-05-17 14:57:00,1,type1,1,0
2,cash-in,30105,60094,494528,2019-07-20 13:20:00,1,type1,1,0
3,cash-in,30105,20575,494528,2019-07-03 14:15:00,1,type1,1,0
4,cash-in,30105,45938,494528,2019-05-26 10:40:00,1,type1,1,0
...,...,...,...,...,...,...,...,...,...
2335,transfer,14945,43793,106907,2019-03-29 14:53:00,0,none,0,1
2336,transfer,9532,43793,106907,2019-04-13 13:19:00,0,none,0,1
2337,transfer,27332,43793,106907,2019-05-10 09:34:00,0,none,0,1
2338,transfer,32685,43793,106907,2019-07-08 12:20:00,0,none,0,1
2339,transfer,26390,43793,106907,2019-03-25 13:52:00,0,none,0,1

In [48]:
dflmerge

,typeofaction,sourceid,destinationid,amountofmoney,date,isfraud,typeoffraud,toa_cash-in,toa_transfer
0,cash-in,30105,28942,494528,2019-07-19 14:40:00,1,type1,1,0
1,cash-in,30105,8692,494528,2019-05-17 14:57:00,1,type1,1,0
2,cash-in,30105,60094,494528,2019-07-20 13:20:00,1,type1,1,0
3,cash-in,30105,20575,494528,2019-07-03 14:15:00,1,type1,1,0
4,cash-in,30105,45938,494528,2019-05-26 10:40:00,1,type1,1,0
...,...,...,...,...,...,...,...,...,...
2335,transfer,14945,43793,106907,2019-03-29 14:53:00,0,none,0,1
2336,transfer,9532,43793,106907,2019-04-13 13:19:00,0,none,0,1
2337,transfer,27332,43793,106907,2019-05-10 09:34:00,0,none,0,1
2338,transfer,32685,43793,106907,2019-07-08 12:20:00,0,none,0,1
2339,transfer,26390,43793,106907,2019-03-25 13:52:00,0,none,0,1

In [50]:
dflmerge['typeofaction'].value_counts()

transfer    1580
cash-in      760
Name: typeofaction, dtype: int64

In [51]:
dftof = pd.get_dummies(dflm['typeoffraud'], prefix='tof')

In [52]:
dftof

      tof_none  tof_type1  tof_type2  tof_type3
0            0          1          0          0
1            0          1          0          0
2            0          1          0          0
3            0          1          0          0
4            0          1          0          0
...        ...        ...        ...        ...
2335         1          0          0          0
2336         1          0          0          0
2337         1          0          0          0
2338         1          0          0          0
2339         1          0          0          0

[2340 rows x 4 columns]

In [53]:
dffinal = pd.concat([dflmerge, dftof], axis=1)

In [54]:
dffinal

,typeofaction,sourceid,destinationid,amountofmoney,date,isfraud,typeoffraud,toa_cash-in,toa_transfer,tof_none,tof_type1,tof_type2,tof_type3
0,cash-in,30105,28942,494528,2019-07-19 14:40:00,1,type1,1,0,0,1,0,0
1,cash-in,30105,8692,494528,2019-05-17 14:57:00,1,type1,1,0,0,1,0,0
2,cash-in,30105,60094,494528,2019-07-20 13:20:00,1,type1,1,0,0,1,0,0
3,cash-in,30105,20575,494528,2019-07-03 14:15:00,1,type1,1,0,0,1,0,0
4,cash-in,30105,45938,494528,2019-05-26 10:40:00,1,type1,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2335,transfer,14945,43793,106907,2019-03-29 14:53:00,0,none,0,1,1,0,0,0
2336,transfer,9532,43793,106907,2019-04-13 13:19:00,0,none,0,1,1,0,0,0
2337,transfer,27332,43793,106907,2019-05-10 09:34:00,0,none,0,1,1,0,0,0
2338,transfer,32685,43793,106907,2019-07-08 12:20:00,0,none,0,1,1,0,0,0
2339,transfer,26390,43793,106907,2019-03-25 13:52:00,0,none,0,1,1,0,0,0

In [55]:
dffinal.drop(columns=['typeofaction', 'typeoffraud'], axis=1, inplace=True)

In [56]:
dffinal

,sourceid,destinationid,amountofmoney,date,isfraud,toa_cash-in,toa_transfer,tof_none,tof_type1,tof_type2,tof_type3
0,30105,28942,494528,2019-07-19 14:40:00,1,1,0,0,1,0,0
1,30105,8692,494528,2019-05-17 14:57:00,1,1,0,0,1,0,0
2,30105,60094,494528,2019-07-20 13:20:00,1,1,0,0,1,0,0
3,30105,20575,494528,2019-07-03 14:15:00,1,1,0,0,1,0,0
4,30105,45938,494528,2019-05-26 10:40:00,1,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
2335,14945,43793,106907,2019-03-29 14:53:00,0,0,1,1,0,0,0
2336,9532,43793,106907,2019-04-13 13:19:00,0,0,1,1,0,0,0
2337,27332,43793,106907,2019-05-10 09:34:00,0,0,1,1,0,0,0
2338,32685,43793,106907,2019-07-08 12:20:00,0,0,1,1,0,0,0
2339,26390,43793,106907,2019-03-25 13:52:00,0,0,1,1,0,0,0

In [59]:
dffinal.drop(columns=['date'], inplace=True)

In [60]:
dffinal

,sourceid,destinationid,amountofmoney,isfraud,toa_cash-in,toa_transfer,tof_none,tof_type1,tof_type2,tof_type3
0,30105,28942,494528,1,1,0,0,1,0,0
1,30105,8692,494528,1,1,0,0,1,0,0
2,30105,60094,494528,1,1,0,0,1,0,0
3,30105,20575,494528,1,1,0,0,1,0,0
4,30105,45938,494528,1,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...
2335,14945,43793,106907,0,0,1,1,0,0,0
2336,9532,43793,106907,0,0,1,1,0,0,0
2337,27332,43793,106907,0,0,1,1,0,0,0
2338,32685,43793,106907,0,0,1,1,0,0,0
2339,26390,43793,106907,0,0,1,1,0,0,0

In [62]:
dffinal.columns = [col for col in dffinal.columns if col not in ['isfraud']] + ['isfraud']

In [63]:
dffinal

,sourceid,destinationid,amountofmoney,toa_cash-in,toa_transfer,tof_none,tof_type1,tof_type2,tof_type3,isfraud
0,30105,28942,494528,1,1,0,0,1,0,0
1,30105,8692,494528,1,1,0,0,1,0,0
2,30105,60094,494528,1,1,0,0,1,0,0
3,30105,20575,494528,1,1,0,0,1,0,0
4,30105,45938,494528,1,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...
2335,14945,43793,106907,0,0,1,1,0,0,0
2336,9532,43793,106907,0,0,1,1,0,0,0
2337,27332,43793,106907,0,0,1,1,0,0,0
2338,32685,43793,106907,0,0,1,1,0,0,0
2339,26390,43793,106907,0,0,1,1,0,0,0

In [64]:
dffinal['isfraud'].unique()

array([0, 1], dtype=uint8)

In [65]:
dffinal['isfraud'].value_counts()

0    1829
1     511
Name: isfraud, dtype: int64

In [67]:
mms = MinMaxScaler()

In [69]:
dffinal['amountofmoney'] = mms.fit_transform(dffinal[['amountofmoney']])

In [70]:
dffinal

,sourceid,destinationid,amountofmoney,toa_cash-in,toa_transfer,tof_none,tof_type1,tof_type2,tof_type3,isfraud
0,30105,28942,0.060610,1,1,0,0,1,0,0
1,30105,8692,0.060610,1,1,0,0,1,0,0
2,30105,60094,0.060610,1,1,0,0,1,0,0
3,30105,20575,0.060610,1,1,0,0,1,0,0
4,30105,45938,0.060610,1,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...
2335,14945,43793,0.011787,0,0,1,1,0,0,0
2336,9532,43793,0.011787,0,0,1,1,0,0,0
2337,27332,43793,0.011787,0,0,1,1,0,0,0
2338,32685,43793,0.011787,0,0,1,1,0,0,0
2339,26390,43793,0.011787,0,0,1,1,0,0,0

In [71]:
dffinalc1 = dffinal.copy()
dffinalc2 = dffinal.copy()

In [72]:
x1 = dffinalc1.iloc[:, 0:-1]

In [73]:
x2 = dffinalc2.iloc[:, 0:-1]

In [74]:
x1

,sourceid,destinationid,amountofmoney,toa_cash-in,toa_transfer,tof_none,tof_type1,tof_type2,tof_type3
0,30105,28942,0.060610,1,1,0,0,1,0
1,30105,8692,0.060610,1,1,0,0,1,0
2,30105,60094,0.060610,1,1,0,0,1,0
3,30105,20575,0.060610,1,1,0,0,1,0
4,30105,45938,0.060610,1,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...
2335,14945,43793,0.011787,0,0,1,1,0,0
2336,9532,43793,0.011787,0,0,1,1,0,0
2337,27332,43793,0.011787,0,0,1,1,0,0
2338,32685,43793,0.011787,0,0,1,1,0,0
2339,26390,43793,0.011787,0,0,1,1,0,0

In [75]:
x2

,sourceid,destinationid,amountofmoney,toa_cash-in,toa_transfer,tof_none,tof_type1,tof_type2,tof_type3
0,30105,28942,0.060610,1,1,0,0,1,0
1,30105,8692,0.060610,1,1,0,0,1,0
2,30105,60094,0.060610,1,1,0,0,1,0
3,30105,20575,0.060610,1,1,0,0,1,0
4,30105,45938,0.060610,1,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...
2335,14945,43793,0.011787,0,0,1,1,0,0
2336,9532,43793,0.011787,0,0,1,1,0,0
2337,27332,43793,0.011787,0,0,1,1,0,0
2338,32685,43793,0.011787,0,0,1,1,0,0
2339,26390,43793,0.011787,0,0,1,1,0,0

In [76]:
mddbs = DBSCAN(eps=0.3, min_samples=20)

In [79]:
mdif = IsolationForest(n_estimators=200)

In [81]:
mddbs.fit(x1)

DBSCAN(eps=0.3, min_samples=20)

In [82]:
mdif.fit(x2)

IsolationForest(n_estimators=200)

In [83]:
preddbs = mddbs.fit_predict(x1)

In [84]:
predif = mdif.predict(x2)

In [85]:
dffinal['PredictionDBS'] = preddbs

In [86]:
dffinal['PredictionIF'] = predif

In [87]:
dffinal

,sourceid,destinationid,amountofmoney,toa_cash-in,toa_transfer,tof_none,tof_type1,tof_type2,tof_type3,isfraud,PredictionDBS,PredictionIF
0,30105,28942,0.060610,1,1,0,0,1,0,0,-1,-1
1,30105,8692,0.060610,1,1,0,0,1,0,0,-1,-1
2,30105,60094,0.060610,1,1,0,0,1,0,0,-1,-1
3,30105,20575,0.060610,1,1,0,0,1,0,0,-1,-1
4,30105,45938,0.060610,1,1,0,0,1,0,0,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...
2335,14945,43793,0.011787,0,0,1,1,0,0,0,-1,-1
2336,9532,43793,0.011787,0,0,1,1,0,0,0,-1,-1
2337,27332,43793,0.011787,0,0,1,1,0,0,0,-1,-1
2338,32685,43793,0.011787,0,0,1,1,0,0,0,-1,-1
2339,26390,43793,0.011787,0,0,1,1,0,0,0,-1,-1

In [88]:
dffinal['PredictionDBS'].value_counts()

-1    2340
Name: PredictionDBS, dtype: int64

In [89]:
dffinal['PredictionIF'].value_counts()

-1    1810
 1     530
Name: PredictionIF, dtype: int64

In [90]:
estsamps = mdif.estimators_samples_

In [91]:
estsamps

[array([ 815,  708, 1226,  512, 1262, 2329,  499, 1340, 1789,  193, 1759,
          24, 2189, 2324,  388,   18,  612, 2184, 1598,  361, 1763, 2174,
        1532, 1181, 1868,  357, 2249,  415, 1375, 2321, 1097, 1834, 1151,
         304,  114, 2082,  688, 1553, 1577, 1523, 2223,  283, 1385, 1196,
        2328,   59, 1439,  403, 1625,  582,   80, 2141, 1826,  230, 1764,
         420, 1453, 2294, 1346, 1135, 1976, 1652, 2247, 1802,  414,  326,
        2301, 1490,  926, 1198,  469, 1011, 2282, 1785,  276, 1927, 1724,
         655, 2300,  961,  856, 2277, 1107, 1833,  837, 1180, 2186,  572,
        2095, 1060,  419,  218, 2043, 1404, 2212,  892, 2187,  437, 2203,
        2216,  291, 1935, 2272, 1411, 1407, 1606,  450, 1306, 1165,  293,
         919,  429,  731, 1126, 2315,  102,  820,  547, 1201,  845,  620,
         105,  451, 1230, 2179,    1, 2150, 1144, 1541,   33, 1431, 1835,
        1982, 1435,  566,  623, 1665, 1432, 1222, 1391,  579, 1470, 1748,
        1788,  182, 1329, 2166, 1549, 1712, 1314, 1882, 1574, 1990,  680,
        2092,  638, 1540,  637, 2125,  205, 1918, 1579,   40, 2021,  770,
        1454,  963, 1894,   62,  956,  459,  584,  739,  646, 1071,  791,
        2035, 1005,  922, 2228, 1381, 1876, 1608, 1561, 1558,  521, 1175,
        1344,  594, 1787,  701,  661, 1660,  722,   25,  168,  774, 2036,
        1137,  800, 2320, 2190, 1552, 1161, 2335,  171, 1260,  606, 1638,
        2318,  365, 1130,  180,  400, 2296,  418,  453, 2230, 1911, 1938,
         737,  983,  379, 1041,  170,  743, 1672, 1872, 1500,  984,  806,
        1640, 1749,  734, 1195, 1429, 1586,  924, 2104,  952,  434, 1173,
        1120, 2149,  115,  943,  644, 1163, 2057, 2158, 2205,  319, 1949,
        1563, 1873, 1373]),
 array([  79, 1834, 2292, 1207, 1099,  648, 1686,  161, 1010, 1626, 1446,
         466, 1901, 2089,  668, 1770,  495,  605,   83, 2192, 1343,  231,
         559,  601, 1873,  185,  669,   26, 2314,  921, 1918, 2079, 1273,
         517, 2203,  745, 2010, 2162,  793,  643,  203,  382,  239,  282,
         966,  367, 1087, 1536, 1803,  905, 1313, 1737, 1585,  808, 1501,
        2310, 1004,   20, 2073, 2098, 1157, 1852,  996, 2037, 2127,  369,
        2060,  190,  127, 2213, 1266, 1805,   72,  256, 2309,   37, 1096,
        1776,   89,  873,  102,  418, 2201, 1839,  761, 1638,  658, 1350,
        1504, 1251,  980,  265, 1088,  947,  824, 1405, 1874,  686, 1530,
        2070, 1983, 1812, 1322,  411, 1245, 1371, 1415,  168,  434, 1659,
        2044,  223, 1566, 1327,  115,  363,  202,  633,  838,  269,  599,
          98, 1167, 2187,  743,  537,  192,   41, 1940, 1291,  661, 1476,
        1892, 2103, 1468,  954,  626,  957,  699,  729,  506,  260,  992,
        1745, 2273,  853, 1007,  172,  557, 1927, 1396, 1925,  620, 2121,
        1534, 1069,  409,  510,  941,  300, 2122, 2110, 1957, 2326,  606,
        2081,  956, 1014,  814,  560,   32, 2272, 1477, 2142,  496,  955,
        1529, 2119, 1297, 1515,  709,  815,  576,  975, 1203, 1853, 1135,
         562, 2011,  290,   28, 1931, 1183,    3,    6,  519, 1697, 1366,
         748,  349, 1226, 2022, 1293, 2025, 2039,  497,  837, 2323,  856,
         346, 1773, 1591, 1434,  611, 1304, 1814,  287,  597, 1439, 1127,
        2238, 1779,  845, 1660,  301, 1116,  513, 1732,  375, 1249, 1485,
        1489, 1106,   42, 1752, 1230, 1977, 1621,  880, 2005,  742,  820,
        1455, 1502, 1922,  348, 2160, 2090,  619, 1224,  535,  511, 1702,
        1171, 2179,  781]),
 array([ 747,  789,  758, 1114, 1394, 1331, 1978, 1566, 2152, 2010, 1462,
        1872, 1300, 1906, 2181,  686, 1874,  831, 1208, 1860, 2164, 2030,
        2272, 2242, 1157,  213, 1100, 2190, 1652, 1227, 1051,  855, 2244,
         117,  605,   75,  149, 1254, 1972,  182, 1807,  587, 1396, 2165,
         136, 1577, 1033, 1323,  649,  724, 1367,  446,  979,  108, 1749,
        2187, 1889,  337,  238, 2062, 2163,  893, 2197, 1792, 1934, 1422,
         441, 1805,  899,  470,  603,  297, 2328,  802,   80, 1680, 1303,
        1092,  327, 1944,  820,  706, 1724, 1561, 1666, 1773, 2214,  689,
        1250, 1823,   45,  226, 2148,  281, 1191, 2095, 1615,  579, 1395,
         233, 2089,  798,  637, 2278, 1203, 1132,  730,   37, 2283,   26,
        1072,  646, 2333, 1012, 1885, 1061, 1117,  680, 2202, 1103, 1378,
        1767, 1328, 2179,  174,  112, 1366, 2130, 1039,  529, 1634, 1777,
         403, 2243, 1549, 1668, 1389,  743, 1700,  363, 1180, 1924,  814,
          58, 2083, 1304, 1401,    1,  627, 2299, 1683, 1347,  843, 1884,
         492,  168,  607, 1757,  997, 2237, 1069,  861,  205, 1814, 2072,
        1243, 1257, 1675,  755, 1578,  805,  445,  617, 2230, 1463,  107,
        2288,   84,  856,  550, 1799,  465, 1932,  858, 1491,  430, 1074,
        1044, 1430, 2326,  442, 2285,  494,  775,  554, 1832,  211,   70,
         766, 2269, 1629, 1737, 1368, 1931, 1158, 1319,  987,  208,  247,
        1376,  314,  434, 1719, 2294, 1993, 1346, 1988, 1957, 2066, 1318,
         456, 1845,   36,  506,  832,  809, 1277, 1711, 1986, 2267, 1077,
        1912, 1176,  734,  128, 2133,  738, 1870,  432,   57,   67,  735,
         969, 1867, 1553, 1703,  817, 1271, 1902, 1812,  672, 1627, 2055,
         225,  978, 1326]),
 array([2006,  940, 1245,  149,  853,  894,  670, 2338, 1780,  368, 2270,
        1044, 1626, 1281, 1635, 1967, 2240, 1429,  642,  179,  210, 2048,
        1177,  467, 1744, 2127,  572, 2085, 1508,  660,  561, 1545,  317,
         343,  607,  885,  703,  246,   42, 1615,  178,  479,  617, 1567,
          24, 1597, 1400,  432,  775,  994, 2008,  182,  466,  303, 1419,
        1180, 2111, 1650, 1544, 2328, 2186, 1966,  914,  621, 1733, 2238,
        1263, 1115, 1489,  315, 1606,  955, 1394, 1396, 1822, 1041,  575,
         577,  215, 2326, 1761, 2179, 1407, 2233,  848, 1309,  258,  394,
        1792, 2263, 1675, 1590, 1950,  852, 1617, 1237,  719,  606, 1793,
        2098, 1886,  123, 1161, 1327, 2315,  131,  830, 1627, 2150,  366,
        1234, 2088,  272, 1008, 1612,   76, 1576, 1534,  105,  162, 1623,
         376, 1865,  164, 1765,  785,  174, 2165, 2086, 1483,  119,  980,
        2309, 1599,  493, 1647,  908,  808, 1022, 1683,  944,  132, 1558,
        1928, 1645,  809, 1404, 1952, 1749,    0,  465, 1087, 1091, 2023,
          37, 1036,  234, 1619, 1467,  797,  173,  436, 1201, 1176, 1941,
        2001,  290,  774, 1500, 1289,  279, 2232,  871, 2302, 2110, 1136,
        1475,  262, 1254, 1371, 2278, 1401,   66,  227,  516, 1207, 2283,
         927,  441,  760, 1543,  601, 2073, 2289,  961, 1511, 2180, 1466,
         284,  985, 1709,  981, 2230, 1301,  431,  552, 1883,  840, 1624,
        1927, 1199, 1315,  595,  532, 1085, 1909,    3, 1150, 1348,  224,
        1108,  280, 1354, 2260, 1370, 1308,  316, 2317,  602, 1781,  455,
         832, 1829, 1767,  675,  620,  214,  328,  957, 1873, 1302, 2297,
          28, 1911,   39,  562, 1166, 1850,  486,  673, 1802, 2273, 1956,
        2285,  653, 1673]),
 array([ 980,  865, 1379,  279, 2160,  542, 1826, 1278, 2297,  689, 2308,
         102, 1314,  204,  130, 2226,  732, 1521,  295,  127,   70,  854,
        1416,   56,  526, 1172,  888, 1024,  535, 2126, 2306,  754, 1308,
        1209,  947,  479, 1474, 2172,  392,  569,  333, 1488, 2275, 1934,
        1645,  745, 1637,   82, 2002, 1659,  941, 1329, 1640, 1259,  773,
        1011, 1962,  609, 1114,  439,  508,  727,   74, 1010, 2199,  635,
        1215,  427,  251, 1197, 1932, 1224, 1089, 1999,   78,  253,  913,
         113,  783,  769, 1461,  453,  806, 2108,  478, 1187, 1749, 1068,
        1009,  236, 1134, 1321,  847,  853, 1715, 2171, 1551,  797,  992,
        2063,  649, 2232,    1, 1284,  953,   60, 1322, 1447, 1516,  926,
        1124,  232, 1291, 1690,  358, 1154,  722,  836, 2131,  173, 2161,
        1383,  141, 1527,  707, 2233, 1586, 1577,  316,  603, 1451,  914,
        1846, 1053,  772, 2158, 1696, 1015, 1980, 1042, 1523, 2248,  412,
         426, 1594,  284, 1535, 2240, 2301, 1296, 1656,  860,  221,   67,
        1045,  208, 1207, 1418,  246,  201, 1439, 1122,  746, 1056,  668,
        1529,   64, 1115,  539, 1833, 1300,  760,  223,  766, 1211,  660,
        1095, 2177, 2106,  385, 2296, 2190,   51, 1635,  399, 1838, 1679,
         181, 2321,  919,  647,  362, 1137,  555,  991, 1432,  696, 1157,
        1249, 1737,  912, 1750, 1590,  738, 1560,  493, 1132,    0, 1193,
         972, 1143,  360,  369, 1146, 2014, 1458, 2292,  713, 1865, 1795,
        1835, 1658,  586, 1357, 1997, 1840, 1791,   19,  260, 1133, 2256,
        1546,  163,  262, 2089, 2060, 2181, 2035, 1511,  395, 1456,  604,
        1165,  578, 1002, 2193,  648,  483, 1361, 1098, 2129, 1785, 1255,
        1639, 1026, 1959]),
 array([ 894,  766, 1737, 1612,  391, 1578,  555, 1196, 1886,  651, 1170,
        1945, 2208, 1000,  375, 2049, 1711,   57,  535, 2027, 1142,  931,
         985, 1923, 1118, 1631,  482,  321,  834, 2046, 1816, 1024,  998,
        1561, 1995,  816,  738, 1191, 1675, 1864,  564,   16,  791,  525,
        2202,   81, 1549, 1290, 1905, 2161, 1082, 1834, 1337, 1350,  210,
         106, 1895,  699, 1393,   89, 1313,  583, 1921, 2221, 1610, 1367,
        1963, 1803,   20,  946,  819, 1249, 2296, 1089, 1151,   15,  794,
        1782,  951, 1424,  155,  310, 2045,  965, 1280,  248, 1462, 1547,
         420, 1149, 1321, 1039, 2273, 1040, 1859,  582,  347, 1841, 1664,
         916, 2073,   10, 1935, 1677, 2328, 2067, 1881,  604, 2145, 1064,
         824, 1952,  345,  274, 1215,  172, 1833,  443,  266, 1278,  950,
          13,  669,  195, 1510,  609,  647, 2077, 2260, 1754,  518, 1904,
        1839, 1532, 2230,  343, 1023, 2319,  353, 1878, 1998,  422, 1658,
        1375, 1416,  290, 1932, 1689, 1718,  531, 1131, 1582,  200, 2138,
        2268,  107, 2071, 2070,  399, 2274,  164,  141, 1748, 2058,  717,
        1348,  306,   31,  160,  508,  782,  774,  490, 1242, 1540,  919,
         494, 2275, 2121,  305,  805, 2192,  714, 1087, 1513, 1564,  563,
        2135, 1153,  785, 1468,  407, 1342, 1068,  344, 1703,  450, 2095,
        1038,  183,  616, 1764, 1021,   87,  425,  881,  578,  680, 1489,
         761,  203, 1027,  896,  269,  811,  987, 2175,  219, 1073, 2053,
        1902,  907,  741,  970, 1684, 1399, 1405, 1717, 1683,  271, 2116,
        1872, 1301,  218, 1638, 1083, 1954, 1121, 2123, 1161, 1128,  996,
        1067, 1304, 1740, 1352, 2194, 2168,  675,  227, 1022, 2292,   80,
        2287,  121, 1573]),
 array([ 385,  985, 1983, 1611, 2294, 2302, 1030, 1514, 1489,  248, 1981,
         152, 2268, 1487, 2329, 1491, 1196,  457,  715, 1314, 1404, 1044,
         946,  964,  128,  254,  263, 1175, 1609, 2283, 1398, 1602,  580,
        1484, 2236,   45, 1361, 1371, 1130,  935,  805,  122, 2251, 1963,
        1863,  550,  552, 1936,  173,  611, 1354,   31,  572,  689,  304,
         870,  793,  712,  180,  478,  134,  447,   32, 2164, 1059,  476,
         989,  582, 1449, 2256, 1898,  125,  416, 2307, 1137, 1002, 2211,
        1942,  384, 1413, 1796, 1405, 2116, 1443, 1941, 2110, 2227, 1186,
         261,  159,    2, 2313, 1341, 1427, 2178, 2103,  702, 1140, 1055,
         686, 1323,  765,  813, 1458, 1247, 1794, 1062, 1327, 1074,  221,
        1134, 1058,  518, 1337, 1731, 1155, 2304, 1380,  869, 2145, 1448,
        2209,  178, 2139, 1800, 1305, 1296,  600, 2260,  335, 1566, 1527,
         738, 2132,  933,  428, 1268, 2050, 2221, 1643,  115,  474, 2097,
         952,  732,  945, 1876, 2112,  417, 1765,  166, 1202, 1021,  908,
        2087,  183,  344, 2095,  181, 1969,  157, 2339, 2305,   93,  488,
         675, 1766,  825,  569, 1536, 1528,  891,  266, 1270,  434,  787,
        1848, 1274, 1462, 1967,   87, 1782,  835, 1132, 1340,  879, 2325,
         119, 1775,  576,  608,  590, 2167,  820, 1103, 1891, 1870, 1047,
        1856, 2038,  158, 2131, 1541, 2141, 2319, 1145, 2286, 1506, 2091,
        1791,  592,   49,  329,  393, 1367, 2188,    3, 1025, 1934, 1529,
        1662,  495, 1703,   73, 1473,  389, 1384,  630,  645,  210, 1825,
        1453, 1781,  746,  477,  838, 1883,  974,  605, 2276, 2277,   66,
        1740, 2069, 1544, 1469,  606,  604,  168, 1294, 1784,  465, 1139,
         500,   77, 2155]),
 array([ 271, 2034,  904,  932,  923, 1621, 1509, 1873, 1367,  798,  344,
         146, 1301,  769,  648, 2017, 1560, 2282,   31, 1228, 1943,  290,
        2264, 1060,  283,  446, 1718, 1121,  676, 1916, 1938,  968,  879,
         850, 2181,  351, 1966, 2144,   56, 1387, 2025, 1066, 1575, 1536,
        1770,  827,  931,  112, 1079,  388,  779,  180,  170,  954, 1138,
        1161,  314, 2035, 2268, 2076,  748, 1753,  412, 1879,  128, 1061,
        1499, 1039,  828, 1097, 1118, 1446, 1788, 1033,  887, 1420, 2093,
         627,  991, 1336, 2074, 1314, 2263,   21,  401,  384, 2229, 1733,
        2004, 1604, 1804,   84, 1796, 1063, 1844,  848, 1375,  234, 1758,
        2102, 1414,  439,  888, 2112,  221, 1698, 2136,  270, 1854, 1776,
        2215,  979,  345, 1289, 1303,  591, 1535, 1402, 2202, 1985,  172,
        1653,  654, 2000, 1591, 2165,  658, 1527,  811,  158,  967, 1117,
        1235, 1096, 1304, 1382,  891,  790,  753, 1566, 1504, 1157, 1429,
         822,  366,  487,  178,  830, 1505,  229, 1991,  307,  573, 1381,
        1210,   80, 1156, 1551,  567, 1541, 2310, 1955, 1792,  597, 1978,
         148, 1493, 1596,  470, 2235,  196,  839, 1962, 1274, 1864, 1923,
        1312,  809,  786,  957, 2118, 1948, 1062,  750, 1637, 1760, 1787,
        1767,  245,  926,  649, 2306, 1606,  257,  154, 2142, 1651, 1005,
          15,  109,  549, 1075,  159,  282, 2254, 2330, 1300,  937, 1607,
         715,  359,  415,  637,   76, 1189, 1954, 1885,  490, 2011, 1083,
         594, 1506, 1669,  922,  817, 1641, 1454,   60, 1458,  340,  707,
         240,  182,  789,  952, 2038, 1588, 2262,  208,  949, 1558, 1104,
        2137,  482, 1119, 1258, 1513, 1853,  358, 1784, 1085,  276,  382,
         250, 2292,  469]),
 array([2316, 1013, 1804,  990, 2297,  959, 2318, 2172, 1153, 1967,  788,
         911,  421, 1214,  638, 1126,   25,  723, 1085,  639, 2171, 2321,
        2089, 2098,  777,  500, 1971, 1061,   24,  977, 1280, 1870, 1392,
           3,  182, 1471,  871,  243, 1449, 1171, 1584, 1744, 2009,  956,
        2010,  274, 2140, 1702,  187,  428, 1743,  175, 1043, 1227, 1440,
         704, 2211,  698, 2027, 2114, 2217,  749,   39,  593, 1761,  265,
          22,  288, 1369, 1047, 1052,   91, 1146, 1077, 1684, 1827, 2156,
        1065, 1325, 1513,  524, 1414, 2299, 1987,  880,  296,  824, 2184,
          48, 2138,  128,  876, 1991, 1080,   12, 2093,  367, 1718, 2041,
        1937, 2104,  577, 1302, 1433,  857, 2031, 1348, 1686,  167, 1890,
         643, 1595, 1365,   69,  467,  261,  754,  761, 2055, 1569, 2039,
        1712, 2066, 1858,  305, 2236, 1466,  838, 1882, 1934, 1101,  608,
        2277,  923, 1841,  397, 2076, 1234, 1423,  256, 2122,  116,  285,
        2127,  454,  330, 1140, 2261,  941,  449,  861,  566, 1594,  483,
          94, 1382, 2281, 1323,  649, 1645,  559,  674, 2050, 1912,  462,
         363,  242, 1242,  443, 2198, 1188,  588, 2300, 1647,  521, 1182,
         178,  466, 2013, 1416, 1538,  419, 1377, 1861,  402,  811,  828,
        1238,  858, 2092,  414, 1190, 2006, 1370,  950,  897,  350, 1258,
        1643, 1379,  714, 1844, 1752, 2220,  511,   87, 2207,  170,  937,
         529, 2129, 2190, 2110, 1083,  217,  220,   76, 1193,  913, 2036,
        1945,   74, 1194,   58, 1649, 1245, 1054, 1427,  817,   36, 1729,
        2125, 2167, 1476, 1304,  434, 1393,  407, 2273,  787,  782,  746,
        1641,  839, 2324,  659, 1201,   23, 1703, 1639, 1582,  431,   33,
        1805,  692,  616]),
 array([1676,  617, 1217,  800, 1745,  922, 1572, 2216, 2241, 1541, 1199,
        1079,  742,  734, 1741, 1400,  282,  804, 1875,  262, 1336, 1020,
        2222, 1247,  926, 1972, 1421,  542, 1984, 1021,  758,  581, 1180,
         234, 1977, 1282, 1746, 1803,  770,  548, 1989, 1787, 1844, 1475,
         492, 2113, 1686,  966, 1322, 1083,   85, 1884, 1133,   49,  792,
        1342, 2294,  425,  992, 1688,    4, 1321, 2255, 1644, 1044, 1086,
         237,  760, 1721, 1373,  513, 1748, 1675,  597,  275, 1220, 1277,
        1821, 2112,  887,  636, 1434,  747, 1554, 1715, 1753,  808, 1068,
         625, 2231, 1154, 1995,   42, 1367,  891,  940, 1540, 1564, 1682,
        2264, 1397, 2198,   70, 1402,  332, 1250, 2162, 1357, 1174, 1539,
         465, 1719, 2018,  682, 1660, 2187, 1159,   83,  471,  434, 1810,
          90, 1253,  847, 1670, 2194, 2334,  390,   38,  946,  691,  959,
         181,  961, 1259, 2046, 1207, 1242, 1765, 2301,   48, 1038,  628,
         589, 1229, 1222,  118, 2066,  591,  901, 1552, 1394,  509,  872,
        1316, 1470, 1751,   18,  485, 1493, 1525, 1791,  134, 1772, 2320,
         624, 1882,  533, 1096, 1969, 1862,  889,  283,  396, 1013,  101,
        2050, 1482, 1466,  214, 1513,  527, 1532,  270,  766,   61,  546,
         327, 2146, 1097, 2323,  135,  555,  105, 1218,  807, 1903,  703,
         897,  198, 2266, 2257,  578, 2313,  848, 1574,   16, 1671,  102,
        1587, 1195, 2051, 1438,  436, 1594, 2310,  689, 1637, 1461, 1833,
         489,  418, 1383,  170, 1319,  274,  968,  810,  448,  437, 1419,
        1216, 1514, 2209, 2102,  583, 1215,  285,  173, 2103, 2273,  782,
         445, 1868, 1575,  748, 1011, 1937, 1231, 1808, 1275,  987,  974,
        1051, 1763,  779]),
 array([1717,  933, 1723, 1591,  114, 2226,  958, 1853, 1939, 1737,  572,
         723, 1798,  178, 2198,  630, 1594, 1019,  536, 1812, 1300, 1837,
         239,  326, 2299,  839, 1312, 1603,   63, 1966, 1585,  606, 2229,
         737,  156, 2186, 2169,  977, 2112, 1757,  432,  336, 2089, 2240,
        1491,  323, 2084, 1567, 1633,  477,  735,   23, 1214, 1945,  769,
        2303, 1620,  697,  439, 1622,  151,  276, 1402,  166,  373, 1845,
        1967, 1958, 1782,  247,  579,  992,  616, 2052, 1259,  602, 2079,
        1355,  541,  508, 1239,  474, 2108,  722,  767,  670, 1061,  677,
        1931, 2292,  245, 1229, 2068, 1765, 1145, 1119,  840,  351, 1635,
         380, 2160, 1180, 1169, 1683, 2203, 1956, 2103, 2267, 1780,   91,
        1761,  593, 1469,  562, 1238, 2126,  913,   15,  150, 1557, 1218,
         744,  266,  732,  138, 2188, 1099,  293,  700,  116,  771,  273,
        1866, 2236, 2200, 1043,  755, 1186, 2238,   34,  129, 1199,  964,
        1252, 1000, 1532,  595, 2065,  236,  793, 2076,  786,  355, 2156,
        1610, 2206,  135,  248, 1084, 1479,  361, 1830,  354,  621, 2020,
        1515, 1253, 2064,  141, 2066,  520,  662, 1586, 1689,   44, 1382,
        1655, 2044, 1743,  121, 1143,  609, 1825,  498,  233,  213, 1254,
         910, 1139,  408,  999, 1523,  335,  365, 2096,  127, 1395, 1435,
         750, 1154, 2336,   66, 2329,  237,  294,  160, 2131,  989,  833,
        1419, 1392,  763, 1129, 1126,  288, 1090,  159, 1996, 1456,  243,
         552, 2242,  433, 1364,  378, 1968,  987, 1833, 1612, 1279,  560,
        1637, 1548, 1103, 1071, 1480,  729, 1636,   61, 2008, 1912,  816,
        1736, 1390, 1054, 1423, 1014,  774,  410,  924, 1993, 2307, 1359,
        1295,   68, 2054]),
 array([ 429,  617, 1328,  721,  103,  460, 1019, 1473, 1917, 2203,  374,
        1573, 1472,  663, 1782, 1535, 2306, 2329,   58, 1413, 2025,  178,
        2157, 1768,   28,  233, 2214, 1629, 1342, 1929, 2122, 1877, 2144,
        1176,  924, 1258,  142,  569,   65,  679, 1166,  558, 2040, 1792,
        1099,  949, 1315, 1278, 1159,  385, 1766,  199,  461,  861, 1558,
         298,  102,  493,  774,  960, 1903,  400,  906, 1055, 1389, 1666,
         282, 1996, 2058, 2289, 1866, 2176, 1341,  462, 1938, 1408,  352,
         713,  334, 2096,  969,   82,   98, 2258,  921, 2315, 2234,   81,
        2272,  804,  994,  815, 2252, 1132, 2136, 1705,  514, 1632,   39,
        1785,  386, 1870, 1261,  823,   42,   73, 1033, 1936,  753,  353,
        1314, 1538, 1383, 2150, 1824,  673, 2046, 1141, 2020,  580, 1794,
        1043, 1609, 2050, 2303,  183, 1616, 1595, 1561, 1846,  802, 1954,
         780, 1126,   53,  986, 1919, 1371,  408, 2183,  734, 1728,  693,

In [93]:
dffinal['anscore'] = mdif.decision_function(x2)

In [94]:
dffinal

,sourceid,destinationid,amountofmoney,toa_cash-in,toa_transfer,tof_none,tof_type1,tof_type2,tof_type3,isfraud,PredictionDBS,PredictionIF,anscore
0,30105,28942,0.060610,1,1,0,0,1,0,0,-1,-1,-0.021494
1,30105,8692,0.060610,1,1,0,0,1,0,0,-1,-1,-0.048974
2,30105,60094,0.060610,1,1,0,0,1,0,0,-1,-1,-0.016946
3,30105,20575,0.060610,1,1,0,0,1,0,0,-1,-1,-0.028614
4,30105,45938,0.060610,1,1,0,0,1,0,0,-1,-1,-0.016349
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2335,14945,43793,0.011787,0,0,1,1,0,0,0,-1,-1,-0.019342
2336,9532,43793,0.011787,0,0,1,1,0,0,0,-1,-1,-0.028390
2337,27332,43793,0.011787,0,0,1,1,0,0,0,-1,-1,-0.008896
2338,32685,43793,0.011787,0,0,1,1,0,0,0,-1,-1,-0.006320
2339,26390,43793,0.011787,0,0,1,1,0,0,0,-1,-1,-0.010763

In [95]:
dffinal.drop('PredictionDBS', axis=1, inplace=True)

In [96]:
dffinal

,sourceid,destinationid,amountofmoney,toa_cash-in,toa_transfer,tof_none,tof_type1,tof_type2,tof_type3,isfraud,PredictionIF,anscore
0,30105,28942,0.060610,1,1,0,0,1,0,0,-1,-0.021494
1,30105,8692,0.060610,1,1,0,0,1,0,0,-1,-0.048974
2,30105,60094,0.060610,1,1,0,0,1,0,0,-1,-0.016946
3,30105,20575,0.060610,1,1,0,0,1,0,0,-1,-0.028614
4,30105,45938,0.060610,1,1,0,0,1,0,0,-1,-0.016349
...,...,...,...,...,...,...,...,...,...,...,...,...
2335,14945,43793,0.011787,0,0,1,1,0,0,0,-1,-0.019342
2336,9532,43793,0.011787,0,0,1,1,0,0,0,-1,-0.028390
2337,27332,43793,0.011787,0,0,1,1,0,0,0,-1,-0.008896
2338,32685,43793,0.011787,0,0,1,1,0,0,0,-1,-0.006320
2339,26390,43793,0.011787,0,0,1,1,0,0,0,-1,-0.010763